# docker-compose.yaml
services:
  auth-server:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      JWT_PRIVATE_KEY_PATH: /keys/private.pem
      JWT_PUBLIC_KEY_PATH: /keys/public.pem

    volumes:
      - /home/ultra/Secrets/IOT-AUTH-MANAGER/private.pem:/keys/private.pem:ro
      - /home/ultra/Secrets/IOT-AUTH-MANAGER/public.pem:/keys/public.pem:ro

    env_file:
      - .env